name: バグ修正 PR
description: バグ修正のための PR
body:
  - type: markdown
    attributes:
      value: |
        故障概要・要因
  - type: input
    id: related-issue
    attributes:
      label: 関連する Issue
      description: "関連issueを記載してください"
      placeholder: "#12"
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: バグの説明
      description: "修正したバグについて説明してください。"
      placeholder: "ここにバグを説明してください"
    validations:
      required: true
